[pytest]
# 测试用例路径
testpaths = testcases
# 将缓存文件夹固定在项目根目录下的 .pytest_cache
cache_dir = .pytest_cache
# 顺便加上之前说的解决中文乱码配置
# 确保是 community_support 而不是 complain
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
# 命令行参数
addopts = -v -s --alluredir=./reports/allure-results --clean-alluredir
python_files = test_*.py
# 日志配置
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
# 标记定义
markers =
    smoke: 冒烟测试用例
    regression: 回归测试用例
    slow: 执行较慢的用例